language: node_js
notifications:
  email: false
before_script:
- npm run greenkeeper:update-lockfile
- npm ls --production >/dev/null
after_script: npm run greenkeeper:upload-lockfile
deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
#  - GK_LOCK_COMMIT_AMEND=true
  - secure: K8/g1g9Tgb1CeKLbQdO0bR0Za8CItHddl9ej73LvjSBxa2MWWyu4SvFxoztWMGHQWkuHJUbxj2YgB8HHsm1Edt8pebcbbKaVcdrzImIiZpaxeyM5aig0XVm2LNY6SssAvjWgjm1KpGM7yvFoympq3waewe7kT9QitCcAZVzR7EL/9amwWt1kq2U1YN7i2MI9mdK8JhVkEyuGBH8ExitOPzy3nuaxYNyXhn+i/Va+UFo96iS1M+4ZFVB5yexe2HyliZdoWtSlan35DB7OEDf0COl0nlYh2uFkhSxBuiGpyVyikVxfbUPpXBSaj78chl3r2tVJqI0aHCN11NvS2mICIVxscIM2V1TK+w7iMh/i1aK2tGVmWPOUwlBQDLbbzy9A7lBIAci5RF6TrDjvot+ezB+qVACgyomd+DnyTSpnqTS8clbc/KA8E2v1RIHNolOfiKwapvVauSPuVgtk+mCDkTpFpdeVJjiWiBDWMFkDh06d7dRKDsRTjSmsWVlnF0CzOHkppK5BRgMCj8u/g6qUCeAI99dcvU1Fdcjzk8BPv6T9uy5PO0e5P1GqBZIO+DybVvLgmI5UvWIfqTl70x1Z8JzSt8qkInHsuUBSMRwtKeiQT7wRxh0bBilflhvrDyvneGTZNmGbdnFOTEdIDuQwmXRdkClavhD1dGSzGlpXQD8=
  - secure: g21rKG5cVjC2qm9szKY7LCOP2Uo+R+mHKLc+Q7dWcPjOVVd8Z8C0SBxbkhYhUkeIqTWoObqpz3t7AdJ6vxyg1hbud3LXqDr0JCgHxZ+lDGG4cHCFug9Cuahg7FoNfaC/NivikCvGNfvoB5HNK3vMb/ok9y8iuKgCH8Q3Vqbts0JJBLH9MPxElq6pYAEDrd1agt0XW8e06Hpx63ky1FRLcGt+dvNGTUeXkH/f9Qw3LxysSnjEtOVeTdOY07pYxAmmwZWYH2BTS6h1sTOjidBwyYULHcji5ONqGRrdnJem2CfZuq5/Dq008AkMmoM8MfhWtfoGn722OLIRPY6XTviqqfp1TMikp7J9DP5JoNjgdj07vWO7L/8r4RibmF9GVt+XhmKR48G1E+1/wscuXlwvHibRM5VFZTyeXXqQtATn8bvM2k4Y9onzDKp0WVOqmdXA7eG+TRpftDIEdUqSGF0Gxda2HTm78vBszdbjHPOpOyyR0coy0r9ydA9+KRaEFZxHJRQJUzM+dx9IZ7MOtKZwn5pg/tz23g6e7qrJpL8w1LVH3RV/9yZbfm4pDZfJ7kJ1sFXSSdyEG66Z1/IA9RyFO7HLbb1i/0A6bM4kW2ejI2SXEsudsplU0kvB5SMrtXZ0XehSjgO7t8dqPKZp8G+RiZ+LZHwZ/sDZuFqmyz1LNR4=
