language: node_js
notifications:
  email: false
after_success: npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: K8/g1g9Tgb1CeKLbQdO0bR0Za8CItHddl9ej73LvjSBxa2MWWyu4SvFxoztWMGHQWkuHJUbxj2YgB8HHsm1Edt8pebcbbKaVcdrzImIiZpaxeyM5aig0XVm2LNY6SssAvjWgjm1KpGM7yvFoympq3waewe7kT9QitCcAZVzR7EL/9amwWt1kq2U1YN7i2MI9mdK8JhVkEyuGBH8ExitOPzy3nuaxYNyXhn+i/Va+UFo96iS1M+4ZFVB5yexe2HyliZdoWtSlan35DB7OEDf0COl0nlYh2uFkhSxBuiGpyVyikVxfbUPpXBSaj78chl3r2tVJqI0aHCN11NvS2mICIVxscIM2V1TK+w7iMh/i1aK2tGVmWPOUwlBQDLbbzy9A7lBIAci5RF6TrDjvot+ezB+qVACgyomd+DnyTSpnqTS8clbc/KA8E2v1RIHNolOfiKwapvVauSPuVgtk+mCDkTpFpdeVJjiWiBDWMFkDh06d7dRKDsRTjSmsWVlnF0CzOHkppK5BRgMCj8u/g6qUCeAI99dcvU1Fdcjzk8BPv6T9uy5PO0e5P1GqBZIO+DybVvLgmI5UvWIfqTl70x1Z8JzSt8qkInHsuUBSMRwtKeiQT7wRxh0bBilflhvrDyvneGTZNmGbdnFOTEdIDuQwmXRdkClavhD1dGSzGlpXQD8=
